version: 'v0.1'
services:
  server:
    image: euclid1990/ubuntu-server
    ports:
    - ${public_port}:80
    - ${ssh_port}:22
    environment:
    - ROOT_PASSWORD=${root_password}
    - AUTHORIZED_KEYS=${authorized_keys}