.catalog:
  name: "Ubuntu"
  version: "v1.0"
  description: "Ubuntu server with SSH"
  uuid: Ubuntu-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: public_port
      description: "Public port to access the web server"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"
    - variable: ssh_port
      description: "SSH forwarded port to connect the server"
      label: "SSH Port"
      required: true
      default: "8222"
      type: "int"
    - variable: root_password
      description: "Ubuntu Linux root Password"
      label: "Root password"
      required: true
      default: ""
      type: "string"
    - variable: authorized_keys
      description: "Adding SSH Keys to authorized_keys"
      label: "authorized key"
      required: false
      default: ""
      type: "string"

server: